accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path

from . import api
from .views import activate_user_view, register

api = [
    path('login', api.Login.as_view(), name='api_login'),
]


urlpatterns = [
    path('activate/<code>/', activate_user_view, name='activate-new-user'),
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reset/',
    auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt',
    ), name='password_reset'),
    path('reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',        ),
        name='password_reset_confirm'),
    path('reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),
    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html', ),
    name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
    name='password_change_done'),
    path('api/', include(api)),

]

cms/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('project/', views.HomeView.as_view(), name='project'),
    path('gallery/', views.HomeView.as_view(), name='gallery'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

accounts/models.py
from django.conf import settings
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse


class Member(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='members')
    other_name = models.CharField('Other name', max_length=255, blank=True, null=True)
    primary_phone = models.CharField('Primary Phone Number', max_length=255, blank=True, null=True, help_text="Enter your WhatsApp Number here")
    secondary_phone = models.CharField('Secondary Phone Number', max_length=255, blank=True, null=True)
    dob = models.DateField('Date of Birth', help_text='Enter your date of birth')
    address = models.CharField('Home Address', max_length=255, blank=True, null=True)
    work = models.CharField('Workplace/ Office', max_length=255, blank=True, null=True)
    job = models.CharField('Position/ Title',max_length=255, blank=True, null=True)
    bio = models.TextField('Professional Bio/ Citation')
    photo = models.ImageField('Profile Picture', blank=True, null=True, upload_to='accounts/' )
    gender = models.BooleanField('Gender', choices=((0,'Male'), (1,'Female')), max_length=50, default=1)

    def __str__(self):
        return self.get_full_name()

    class Meta:
        verbose_name = 'Member profile'
        verbose_name_plural = 'Member Profiles'

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        if self.user.first_name:
            first_name = self.user.first_name
        else:
            first_name = ''
        if self.user.last_name:
            last_name = self.user.last_name
        else:
            last_name = ''
        if self.other_name:
            other_name = self.other_name
        else:
            other_name = ''

        full_name = '%s, %s %s' % (last_name, first_name, other_name)
        return full_name.strip()
    
    full_name = property(get_full_name)

    def get_abbrev_name(self):
        '''
        Returns the Abbreivated name with initials
        '''
        if self.user.first_name:
            first_name = self.user.first_name
            first_name = first_name[0].capitalize()+'.'
        else:
            first_name = ''
        if self.user.last_name:
            last_name = self.user.last_name.capitalize()
        else:
            last_name = ''
        if self.other_name:
            other_name = self.other_name
            other_name = other_name[0].capitalize()+'.'
        else:
            other_name = ''

        full_name = '%s %s %s' % (first_name, other_name, last_name)
        return full_name.strip()

    def get_phone_number(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        if self.primary_phone:
            primary_phone = self.primary_phone
        else:
            primary_phone = ''
        if self.secondary_phone:
            secondary_phone = ", "+ self.secondary_phone
        else:
            secondary_phone = ''

        phone = '%s %s' % (primary_phone, secondary_phone)
        return phone.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.user.first_name

    def get_username(self):
        '''
        Returns the short name for the user.
        '''
        return self.user.username

    def get_absolute_url(self):
        return reverse('membership:detail', args=[self.user.username])

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this Member.
        '''
        send_mail(subject, message, from_email, [self.user.email], **kwargs)

    def get_is_active(self):
        if self.user.is_active:
            return 'Active'
        else:
            return 'Inactive'
    def get_is_admin(self):
        if self.user.is_admin:
            return True
        else:
            return False

accounts/forms.py
# accounts.forms.py
from django import forms
from django.contrib.auth import get_user_model

from accounts.models import MEMBERSHIP_TYPE, Member


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())

    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'password2', 'is_active')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        qs = get_user_model().objects.filter(email__iexact=email)
        if qs.exists():
            raise forms.ValidationError("Email already exists, cannot use this email")
        return email


class MembershipForm(forms.ModelForm):
    membership_type= forms.CharField(label='Select Membership Type', widget=forms.Select(choices=MEMBERSHIP_TYPE))
    dob = forms.DateField(label='Date of Birth' ,input_formats=['%d/%m/%Y'])

    class Meta:
        model = Member
        fields = ('other_name', 'primary_phone', 'secondary_phone', 'membership_type', 
                    'nse_no', 'coren_no', 'dob', 'address', 'work', 'job', 'bio', 'photo', 'gender')


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.shortcuts import redirect, render

from .forms import MembershipForm, UserRegistrationForm
from .models import Member
from .tasks import send_new_user_welcome_email_task


def register(request):
    member = MembershipForm(request.POST or None, request.FILES or None)
    user_form = UserRegistrationForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if user_form.is_valid() and member.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.is_active = True # should be false in final production
            # Save the User object
            new_user.save()
            # Create the user membership
            primary_phone = member.cleaned_data['primary_phone']
            membership_type = member.cleaned_data['membership_type']
            nse_no = member.cleaned_data['nse_no']
            dob = member.cleaned_data['dob']
            work = member.cleaned_data['work']
            job = member.cleaned_data['job']
            bio = member.cleaned_data['bio']
            photo = member.cleaned_data['photo']
            member = Member.objects.create(user=new_user, primary_phone=primary_phone, membership_type=membership_type, nse_no=nse_no, dob=dob, work=work, job=job, bio=bio, photo=photo)
            messages.success(request, 'Your registration was successful and your Membership Profile created successfully')
            host = 'HTTPS' if request.is_secure() else 'HTTP'
            host += '://'+str(request.get_host())
            print(host, )
            send_new_user_welcome_email_task.delay(new_user.email, member.id, host)
            return redirect('login')
        else:
            messages.add_message(request, messages.ERROR, 'Your last submission was not successful, please rectify and re-submit', extra_tags='danger')
    return render(request, 'accounts/register.html', {'form': member, 'user_form': user_form})


def activate_user_view(request, code=None, *args, **kwargs):
    pass

accounts/templates/accounts/password_change.html
{% extends 'cms/base.html' %}

{% block title %}
    Update Password
{% endblock %}

{% block page_title %}
    Update your password
{% endblock %}

{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
{{ block.super }}
    {% breadcrumb "Change your password" "password_change" %}
{% endblock %}

{% load crispy_forms_tags %}


{% block content %}

<div id="content">
    <div class="container">

        <section>
            <div class="row">
                <div class="col-md-12">

                    <div class="heading">
                        <h2>Change your password </h2>
                    </div>


                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                      <h3 class="card-title">Change password for {{ request.user.username }}</h3>
                      <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-success btn-block">Change password</button>
                      </form>



                </div>
            </div>
        </section>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'cms/base.html' %}

{% block title %}
    Password Changed Successfully!
{% endblock %}

{% block page_title %}
    Password Changed Successfully!
{% endblock %}

{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
{{ block.super }}
    {% breadcrumb "Password Changed Successfully!" "password_change_done" %}
{% endblock %}



{% block content %}

<div id="content">
    <div class="container">

        <section>
            <div class="row">
                <div class="col-md-12">

                    <div class="heading">
                        <h2>Password Changed Successfully! </h2>
                    </div>

                    <p class="lead"><strong>Success!</strong> Your password has been changed!
                    </p>


                </div>
            </div>

            <div class="row">
                <div class="col-md-12">

                    <a href="{% url 'dashboard' %}" class="btn btn-primary">Return to your dashboard</a>

                </div>
            </div>
        </section>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'cms/base.html' %}

{% block title %}
    Register
{% endblock %}

{% block page_title %}
    Register
{% endblock %}

{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
{{ block.super }}
    {% breadcrumb "Register" "register" %}
{% endblock %}

{% load crispy_forms_tags %}

{% block css %}
<!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
{% endblock %}

{% block content %}

<div id="content">
    <div class="container">

        <section>
            <div class="row">
                <div class="col-md-12">

                    <div class="heading">
                        <h2>Register </h2>
                    </div>

                    <p class="lead">To become a member of this prestigious institution, please fill the form below and your account will be confirmed by the Administrator, when you attend the meeting, then your digital certificate will be ready for download. <br>
                    <!-- <strong>See right box for different membership types, fees/ dues and associated benefits</strong> -->
                    </p>


                </div>
            </div>

            <div class="row">
                <div class="col-md-12">

                    <form method="post" action="." enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                         <div class="form-group col-md-6 ">
                           {{ user_form.first_name|as_crispy_field }}
                         </div>
                         <div class="form-group col-md-6">
                           {{ user_form.last_name|as_crispy_field }}
                         </div>
                         <!-- <div class="form-group col-md-4">
                           {{ form.other_name|as_crispy_field }}
                         </div> -->
                       </div>
                       <div class="form-row">
                           <div class="form-group col-md-6">
                               {{ user_form.email|as_crispy_field }}
                           </div>
                           <div class="form-group col-md-6">
                               {{ form.primary_phone|as_crispy_field }}
                           </div>

                       </div>
                       <div class="form-row">
                           <div class="form-group col-md-6">
                               {{ form.dob|as_crispy_field }}
                           </div>
                           <div class="form-group col-md-6">
                               {{ form.nse_no|as_crispy_field }}
                           </div>



                       </div>
                       <div class="form-row">
                           <div class="form-group col-md-6">
                               {{ form.membership_type|as_crispy_field }}
                           </div>
                           <div class="form-group col-md-6">
                               {{ form.work|as_crispy_field }}
                           </div>

                           <!-- <div class="form-group col-md-4">
                               {{ form.coren_no|as_crispy_field }}
                           </div>
                           <div class="form-group col-md-6">
                               {{ form.job|as_crispy_field }}
                           </div> -->

                       </div>
                       <div class="form-row">
                           <!-- <div class="form-group col-md-12">
                               {{ form.address|as_crispy_field }}
                           </div> -->
                           <div class="form-group col-md-12">
                               {{ form.bio|as_crispy_field }}
                           </div>
                           <div class="form-group col-md-6 ">
                             {{ form.photo|as_crispy_field }}
                           </div>
                           <div class="form-group col-md-6 ">
                             {{ form.gender|as_crispy_field }}
                           </div>

                       </div>
                       <div class="form-row">
                        <div class="form-group col-md-12 ">
                          {{ user_form.username|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                          {{ user_form.password|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6">
                          {{ user_form.password2|as_crispy_field }}
                        </div>

                      </div>

                       <div class="form-row">
                           <div class="form-group col-md-12">
                               <button type="submit" class="btn btn-primary btn-block btn-lg ">Create Account</button>
                           </div>
                       </div>


                      </form>
                </div>
                <div class="col-md-12">
                    <div class="panel-group accordion" id="accordionThree">
                        {% for item in membership_type %}
                        <div class="panel panel-default">

                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordionThree" href="#collapse{{ forloop.counter }}">
                                        {{ item.get_type_display }} (&#8358;{{ item.initial_cost }})
                                    </a>

                                </h4>
                            </div>
                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse {% if forloop.counter == 1 %} in{% endif %} ">
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-md-12">
                                            {{ item.benefits }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>

    </div>
    <!-- /#contact.container -->





</div>

{% endblock %}

{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    <script>
        $(function () {
            $("#id_dob").datetimepicker({
                timepicker:false,
                format: 'd/m/Y',
                // theme:'dark',
                lang:'en',
                closeOnDateSelect:true,
                // minDate:0,
                maxDate:0,
            });
        });
    </script>
{% endblock %}