blog/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views
from .feeds import LatestMediaFeed

admin = [
    path('category/delete/<pk>/', views.AdminCategoryDeleteView.as_view(), name='delete_category'),
    path('category/create/', views.AdminCategoryCreateView.as_view(), name='create_category'),
    path('category/<slug>/', views.AdminCategoryDetailView.as_view(), name='category_detail'),
    path('category/', views.AdminCategoryListView.as_view(), name='category_list'),
    path('posts/delete/<pk>/', views.AdminPostDeleteView.as_view(), name='post_delete'),
    path('posts/update/<pk>/', views.AdminPostUpdateView.as_view(), name='post_update'),
    path('posts/new/', views.AdminPostCreateView.as_view(), name='post_create'),
    path('posts/', views.AdminPostListView.as_view(), name='post_list'),
    path('', TemplateView.as_view(template_name='blog/admin/index.html'), name='admin'),
]


urlpatterns = [
    path('', views.BlogListView.as_view(), name='index'),
    path('category/<slug:category>/', views.BlogListView.as_view(),    name='post_list_by_category'),
    path('tag/<tag>/', views.BlogListView.as_view(), name='post_list_by_tag' ),
    path('<int:year>/', views.YearArchive.as_view(), name="article_year_archive"),
    path('<int:year>/<int:month>/', views.MonthArchive.as_view(month_format='%m'), name="article_month_archive"),
    path('<int:year>/<int:month>/<int:day>/', views.DayArchive.as_view(month_format='%m'), name="article_day_archive"),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.BlogDetailView.as_view(month_format='%m'), name='detail'),
    path('admin/', include(admin)),
    path('feed/', LatestMediaFeed(), name='media_feed')
]

cms/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('project/', views.HomeView.as_view(), name='project'),
    path('gallery/', views.HomeView.as_view(), name='gallery'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

blog/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils import timezone
from tinymce.models import HTMLField

from taggit.managers import TaggableManager
from .utils import unique_slug_generator
from django.conf import settings

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_list_by_category',
                        args=[self.slug])


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Media(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'published'),
    )
    title = models.CharField(max_length=255)
    body = HTMLField('Content')
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, null=True, blank=True, default=None)
    slug = models.SlugField(max_length=250,
                            unique_for_date='date')
    date = models.DateTimeField(default=timezone.now)
    top_story = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    last_seen = models.DateTimeField(null=True, blank=True)
    views = models.PositiveIntegerField(null=True, blank=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='authors', on_delete=models.SET_NULL, null=True, blank=True, help_text="Leave author field blank if you want it to appear as 'Admin' ")
    tags = TaggableManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-top_story', '-date']
        verbose_name_plural = 'Media - News & Events'

    def get_absolute_url(self):
        return reverse('blog:detail',
                       args=[self.date.year,
                             self.date.month,
                             self.date.day,
                             self.slug])

    objects = models.Manager()  # the default Manager
    published = PublishedManager()  # custom Manager

    def get_author(self):
        return self.author.get_full_name


def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    # # make slug if not defined
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
    # Make sure only one top story per time
    if instance.top_story and instance.status == 'published':
        qs_exists = Media.objects.filter(top_story=1, status='published').exists()
        if qs_exists:
            Media.objects.filter(top_story=1, status='published').update(top_story=0)


pre_save.connect(rl_pre_save_receiver, sender=Media)


class Image(models.Model):
    image = models.ImageField(upload_to='blog')
    description = models.CharField('Image Description', max_length=255, null=True, blank=True)
    primary = models.BooleanField('Set as Primary Image', default=False)
    media = models.ForeignKey('Media', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.description if self.description else 'Image'

    def image_tag(self):
        return u'<img src="%s" width="200px" height="200px" />' % self.image.url
        image_tag.short_description = 'Image'
        image_tag.allow_tags = True

    class Meta:
        ordering = ['media']
        verbose_name_plural = 'Image Gallery'


class Video(models.Model):
    video = models.URLField(help_text="Add a youtube link to the video")
    description = models.CharField('Video Description', max_length=255, null=True, blank=True)
    media = models.ForeignKey('Media', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.description if self.description else 'Video'

    def video_tag(self):
        return u'<iframe src="%s" width="200px" height="200px"></iframe>' % self.video
        video_tag.short_description = 'Video'
        video_tag.allow_tags = True

    class Meta:
        ordering = ['media']
        verbose_name_plural = 'Video Gallery'


class Comment(models.Model):
    post = models.ForeignKey(Media, on_delete=models.CASCADE,
                             related_name='comments')
    member = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name='commentors', blank=True, null=True)
    name = models.CharField(max_length=80,blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    body = models.TextField('Comment')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.get_commentor_name(), self.post)

    def get_commentor_name(self):
    	name = self.member.get_full_name() if self.member else self.name
    	return name

blog/forms.py
from .models import Comment, Media, Image, Video
from django import forms
from betterforms.multiform import MultiForm

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    q = forms.CharField()

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        exclude = ("media",)

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        exclude = ("media",)

class PostForm(forms.ModelForm):
    class Meta:
        model = Media
        exclude = ("created", "updated", 'last_seen', 'views')
        # fields = ('image', 'video')

class AdminCreateForm(MultiForm):
    form_classes = {
        'post': PostForm,
        'image': ImageForm,
        'video': VideoForm,
    }

blog/views.py
from django.contrib.postgres.search import (SearchQuery, SearchRank,
                                            SearchVector, TrigramSimilarity)
from django.db.models import Count
from django.shortcuts import get_object_or_404, render, reverse
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import (DetailView, ListView, YearArchiveView, MonthArchiveView, 
DayArchiveView, DateDetailView, CreateView, DeleteView, UpdateView)

from taggit.models import Tag

from .forms import CommentForm, SearchForm, AdminCreateForm
from .models import Category, Media
from accounts.models import Member


class BlogListView(ListView):
    template_name = 'blog/list.html'
    model = Media
    context_object_name = 'stories'  # Default: object_list
    paginate_by = 2

    def get_queryset(self):
        word = self.kwargs
        queryset = Media.published.order_by('-id')
        if 'category' in word:
            query = word['category']
            queryset = Media.published.filter(category__slug=query).order_by('-id')

        if 'tag' in word:
            tag = word['tag']
            tag = get_object_or_404(Tag, slug=tag)
            queryset = Media.published.filter(tags__in=[tag])

        search = self.request.GET.get('q')
        if search:
            form = SearchForm(self.request.GET)
            if form.is_valid():
                query = form.cleaned_data['q']
                search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
                search_query = SearchQuery(query)

                queryset = Media.published.annotate(
                    rank=SearchRank(search_vector, search_query),
                    similarity=TrigramSimilarity('title', query) + TrigramSimilarity('body', query),
                # ).order_by('-rank')
                ).filter(similarity__gt=0.01).order_by('-rank')


        return queryset


    def get_context_data(self, *args, **kwargs):
        word = self.kwargs
        context = super(BlogListView, self).get_context_data(*args, **kwargs)
        categories = Category.objects.all()
        context['categories'] = categories
        tags = Tag.objects.all()
        context['tags'] = tags
        if 'category' in word:
            query = word['category']
            context['category'] = query

        if 'tag' in word:
            tag = word['tag']
            context['tag'] = tag

        search = self.request.GET.get('q')
        if search:
            context['search'] = search

        extra = {
            'active_page': 'blog',
        }
        context.update(extra)
        return context

class BlogDetailView(DateDetailView):
    template_name = 'blog/blog_detail.html'
    model = Media
    context_object_name = 'story'  # Default: object_list
    date_field = 'date'

    def get_queryset(self):
        queryset = Media.published.order_by('-id')
        return queryset

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Write Your Logic here
            new_comment = comment_form.save(commit=False)
            self.object = self.get_object()
            new_comment.post = super(BlogDetailView, self).get_object()
            if request.POST['member']:
                new_comment.member = Member.objects.get(pk=request.POST['member'])
            # Save the comment to the database
            new_comment.save()

            context = context = self.get_context_data(**kwargs)
            extra = {
                'new_comment': True,
            }
            context.update(extra)
            print(context)

            return render(request, 'blog/blog_detail.html', context=context)

        else:
            self.object = self.get_object()
            context = super(BlogDetailView, self).get_context_data(*args, **kwargs)
            return context

    def get_object(self):
        obj = super().get_object()
        # Record the last accessed date
        obj.last_seen = timezone.now()
        obj.views = int(obj.views or 0) + 1
        obj.save()
        return obj

    def get_context_data(self, *args, **kwargs):
        context = super(BlogDetailView, self).get_context_data(*args, **kwargs)
        print(context)
        comments = self.get_object().comments.filter(active=True)
        # List of similar posts
        post_tags_ids = self.get_object().tags.values_list('id', flat=True)
        similar_posts = Media.published.filter(tags__in=post_tags_ids).exclude(id=self.get_object().id)
        similar_posts = similar_posts.annotate(same_tags=Count(
            'tags')).order_by('-same_tags', '-date')[:3]

        comment_form = CommentForm()

        extra = {
            'comments': comments,
            'active_page': 'blog',
            'form': comment_form,
            'similar_posts': similar_posts,
        }
        context.update(extra)
        return context

class YearArchive(YearArchiveView):
    template_name = 'blog/list_year_archive.html'
    model = Media
    date_field = 'date'
    make_object_list = True
    paginate_by = 50

class MonthArchive(MonthArchiveView):
    template_name = 'blog/list_month_archive.html'
    model = Media
    date_field = 'date'
    make_object_list = True
    paginate_by = 50

class DayArchive(DayArchiveView):
    template_name = 'blog/list_day_archive.html'
    model = Media
    date_field = 'date'
    make_object_list = True
    paginate_by = 2


class AdminPostListView(ListView):
    model = Media
    template_name = "blog/admin/post_list.html"
    context_object_name = 'stories'  # Default: object_list
    paginate_by = 20

class AdminPostCreateView(CreateView):
    model = Media
    template_name = "blog/admin/create_post.html"
    form_class = AdminCreateForm
    # success_url = reverse_lazy('blog:post_list')

class AdminPostUpdateView(UpdateView):
    model = Media
    template_name = "blog/admin/create_post.html"
    fields = '__all__'
    success_url = reverse_lazy('blog:post_list')

class AdminPostDeleteView(DeleteView):
    model = Media
    success_url = reverse_lazy('blog:post_list')

''' Category Actions '''
class AdminCategoryCreateView(CreateView):
    model = Category
    template_name = "blog/admin/create_category.html"
    fields = '__all__'
    success_url = reverse_lazy('blog:category_list')

class AdminCategoryListView(ListView):
    model = Category
    template_name = "blog/admin/category_list.html"

class AdminCategoryDetailView(DetailView):
    model = Category
    template_name = "blog/admin/category_detail.html"

class AdminCategoryDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy('blog:category_list')

blog/templates/blog/blog_detail.html
{% extends 'cms/base.html' %}

{% block title %}
    {{ story.title }}
{% endblock %}

{% block description %}
    {{ story.body |truncatewords:60 }}
{% endblock %}

{% block keywords %}
    {% for tag in story.tags.all %}
        {{ tag.name }}{% if not forloop.last %}, {% endif %}
    {% endfor %}
{% endblock %}

{% block page_title %}
    {{ story.title }}
{% endblock %}

{% block page_lead %}
    {{ story.get_type_display }}
{% endblock %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "News and Events" "blog:index" %}
    {% breadcrumb story.title "blog:detail" %}
{% endblock %}

{% block content %}
{% load static %}
{% load humanize %}

<section class="blog-post">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="post-content margin-bottom--big">
            {% if story.image_set.count > 1 %}
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                  <!-- Indicators -->
                  <ol class="carousel-indicators">
                  {% for pix in story.image_set.all %}
                    <li data-target="#myCarousel" data-slide-to="{{ forloop.counter0 }}" {% if forloop.counter0 == 0 %} class="active" {% endif %}></li>
                    {% endfor %}
                  </ol>

                  <!-- Wrapper for slides -->
                  <div class="carousel-inner">
                  {% for pix in story.image_set.all %}
                    <div class="item {% if forloop.counter0 == 0 %} active {% endif %}">
                      <img src="{{ pix.image.url }}" alt="{{ pix.description }}">
                    </div>
                    {% endfor %}
                  </div>

                <!-- Left and right controls -->
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <i class="pe-7s-angle-left"></i>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <i class="pe-7s-angle-right"></i>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            {% elif story.image_set.count == 1 %}
            <div class="image"><a href="{{ story.get_absolute_url }}"><img src="{{ story.image_set.first.image.url }}" alt="{{ story.image_set.first.description }}"  class="img-responsive img-thumbnail"></a></div>

            {% endif %}

          <h2> {{ story.title }} </h2>
          <blockquote>
              <p>{{ story.get_type_display }}</p>
              {% if story.type != 'news' %}
                  <p>Event Date: {{ story.date }}</p>
              {% else %}
                  <p>Published: {{ story.date }}</p>
              {% endif %}
          </blockquote>
          {% if story.video_set.count %}
              {% for vid in story.video_set.all %}
                  <iframe src="{{ vid.video }}" ></iframe>
                  <p>{{ vid.description }}</p>
              {% endfor %}
          {% endif %}
          <p>{{ story.body |linebreaksbr }} </p>


        </div>
        <!-- /.post-content-->
      </div>
    </div>
  </div>
</section>
{% if similar_posts %}
<section class="background-gray-lightest section--padding-bottom-small">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h4 class="text-center text-uppercase margin-bottom">Similar Posts</h4>
        <hr>
      </div>
    </div>
    <div class="row">
        {% for story in similar_posts %}
            <div class="col-sm-4">
                <div class="post">
                    <div class="image"><a href="{{ story.get_absolute_url }}"><img src="{{ story.image_set.first.image.url }}" alt="{{ story.image_set.first.description }}" class="img-responsive"></a></div>
                    <h3><a href="{{ story.get_absolute_url }}">{{ story.title }}</a></h3>
                    <p class="post__intro">{{ story.body | truncatewords:30 }}</p>
                    <p class="read-more"><a href="{{ story.get_absolute_url }}" class="btn btn-ghost">View     </a></p>
                </div>
            </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endif %}

<section>
  <div id="contact" class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="box-simple">
          <div class="icon"><i class="pe-7s-pen"></i></div>
          <div class="content">
            <h4>
                Comments
                {% with comments.count as total_comments %}
                    {% if total_comments > 0 %}
                        <span class="badge">{{ total_comments }}</span>

                    {% endif %}
                {% endwith %}

            </h4>
            {% if new_comment %}
            <p>Thank you for your comment</p>
            {% else %}

                <p class="text-muted">Feel free to leave some feedback. Thanks</p>

                {% include 'cms/form.html' %}
            {% endif %}
            <hr>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
    {% for comment in comments %}
      <div class="col-md-12">
        <div class="box-simple">
          <div class="icon"><i class="pe-7s-user"></i></div>
          <div class="content">

            <h4>{{ comment.name }} <small>{{ comment.created|naturaltime }}</small>
            </h4>
            <p>{{ comment.body|linebreaks }}</p>
          </div>
        </div>
      </div>
    {% endfor %}

    </div>
  </div>
</section>


{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'cms/base.html' %}

{% block title %}
    News and Events
{% endblock %}

{% block description %}
    List of our news, events, stories and much more
{% endblock %}

{% block keywords %}
    news, events, stories, IFA, Publish, communications, desk
{% endblock %}

{% block page_title %}
    {% if tag %}
        Posts tagged with "{{ tag.name|capfirst }}"
    {% elif type %}
        {{ type|capfirst }}
    {% elif search %}
        Posts containing "{{ search }}"
    {% else %}
        News and Events
    {% endif %}
{% endblock %}

{% block page_lead %}
    Find below, the list of our news stories and life changing events
    <form method="get" action="">
     <div class="input-group">
       <input type="text" name="q" value="{{ search }}" id="query" class="form-control" placeholder="Search">
       <div class="input-group-btn">
         <button class="btn btn-default" type="submit">
           <i class="pe-7s-search"></i>
         </button>
       </div>
     </div>
    </form>

{% endblock %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "News and Events" "blog:index" %}
{% endblock %}

{% block content %}
{% load static %}

<section class="section--padding-bottom-small">
  <div class="container">
      {% for story in stories %}
      <div class="row">
          <div class="col-sm-4">
            <div class="post">
              <div class="image"><a href="{{ story.get_absolute_url }}"><img src="{{ story.image_set.first.image.url }}" alt="{{ story.image_set.first.description }}"  class="img-responsive img-thumbnail"></a></div>
            </div>
          </div>
          <div class="col-sm-8">
            <div class="text-left">
              <h3><a href="{{ story.get_absolute_url }}">{{ story.title }}</a> <small> <a href="{{ request.path }}?type={{story.type}}">|{{ story.get_type_display }}</a></small></h3>
              <p class="post__intro">{{ story.body | truncatewords:60 }}</p>
              <p class="tags">
                Tags:
                <!-- {{ post.tags.all | join:", "}} -->
                {% for tag in story.tags.all %}
                    <a href="{{ request.path }}?tag={{tag.slug}}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
              </p>
              <p class="read-more"><a href="{{ story.get_absolute_url }}" class="btn btn-ghost">Continue reading     </a></p>
            </div>
          </div>
      </div>
      {% endfor %}

      <div class="row">
          <div class="col-sm-12">
              {% if is_paginated %}
              <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                  <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                  {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                  {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                  <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
              </ul>
            {% endif %}
          </div>
      </div>
  </div>
</section>

<!-- <section class="background-gray-lightest section--padding-bottom-small">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h4 class="text-center text-uppercase margin-bottom">Archives/ Search</h4>
        <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <div class="post text-left">
          <h3><a href="text.html">Search News & Events</a></h3>

        </div>
      </div>
      <div class="col-sm-4">
        <div class="post">
          <div class="image"><a href="text.html"><img src="img/blog2.jpg" alt="" class="img-responsive"></a></div>
          <h3><a href="text.html">Tempor sit amet</a></h3>
          <p class="post__intro"> Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi.</p>
          <p class="read-more"><a href="text.html" class="btn btn-ghost">Continue reading     </a></p>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="post">
          <div class="image"><a href="text.html"><img src="img/blog3.jpg" alt="" class="img-responsive"></a></div>
          <h3><a href="text.html">Vestibulum erat wisi</a></h3>
          <p class="post__intro">ellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
          <p class="read-more"><a href="text.html" class="btn btn-ghost">Continue reading     </a></p>
        </div>
      </div>
    </div>
  </div>
</section> -->



{% endblock %}