changemakers/urls.py
from django.contrib import admin
from django.urls import path, include
import cms
import blog

urlpatterns = [
    path('', include(('cms.urls','cms'), namespace='cms')),
    path('blog', include(('blog.urls','blog'), namespace='blog')),
    path('admin/', admin.site.urls),
]

cms/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('project/', views.HomeView.as_view(), name='project'),
    path('gallery/', views.HomeView.as_view(), name='gallery'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

blog/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils import timezone
from tinymce.models import HTMLField

from taggit.managers import TaggableManager
from .utils import unique_slug_generator
from django.conf import settings

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_list_by_category',
                        args=[self.slug])


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Media(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'published'),
    )
    title = models.CharField(max_length=255)
    body = HTMLField('Content')
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, null=True, blank=True, default=None)
    slug = models.SlugField(max_length=250,
                            unique_for_date='date')
    date = models.DateTimeField(default=timezone.now)
    top_story = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    last_seen = models.DateTimeField(null=True, blank=True)
    views = models.PositiveIntegerField(null=True, blank=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='authors', on_delete=models.SET_NULL, null=True, blank=True, help_text="Leave author field blank if you want it to appear as 'Admin' ")
    tags = TaggableManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-top_story', '-date']
        verbose_name_plural = 'Media - News & Events'

    def get_absolute_url(self):
        return reverse('blog:detail',
                       args=[self.date.year,
                             self.date.month,
                             self.date.day,
                             self.slug])

    objects = models.Manager()  # the default Manager
    published = PublishedManager()  # custom Manager

    def get_author(self):
        return self.author.get_full_name


def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    # # make slug if not defined
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
    # Make sure only one top story per time
    if instance.top_story and instance.status == 'published':
        qs_exists = Media.objects.filter(top_story=1, status='published').exists()
        if qs_exists:
            Media.objects.filter(top_story=1, status='published').update(top_story=0)


pre_save.connect(rl_pre_save_receiver, sender=Media)


class Image(models.Model):
    image = models.ImageField(upload_to='blog')
    description = models.CharField('Image Description', max_length=255, null=True, blank=True)
    primary = models.BooleanField('Set as Primary Image', default=False)
    media = models.ForeignKey('Media', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.description if self.description else 'Image'

    def image_tag(self):
        return u'<img src="%s" width="200px" height="200px" />' % self.image.url
        image_tag.short_description = 'Image'
        image_tag.allow_tags = True

    class Meta:
        ordering = ['media']
        verbose_name_plural = 'Image Gallery'


class Video(models.Model):
    video = models.URLField(help_text="Add a youtube link to the video")
    description = models.CharField('Video Description', max_length=255, null=True, blank=True)
    media = models.ForeignKey('Media', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.description if self.description else 'Video'

    def video_tag(self):
        return u'<iframe src="%s" width="200px" height="200px"></iframe>' % self.video
        video_tag.short_description = 'Video'
        video_tag.allow_tags = True

    class Meta:
        ordering = ['media']
        verbose_name_plural = 'Video Gallery'


class Comment(models.Model):
    post = models.ForeignKey(Media, on_delete=models.CASCADE,
                             related_name='comments')
    member = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name='commentors', blank=True, null=True)
    name = models.CharField(max_length=80,blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    body = models.TextField('Comment')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.get_commentor_name(), self.post)

    def get_commentor_name(self):
    	name = self.member.get_full_name() if self.member else self.name
    	return name

cms/models.py
from django.db import models
from django.urls import reverse

from .icons import icon

ICONS = icon()
icon_help = 'Select an Icon that best tells the story: <a href="http://nucleus.amazyne.com/ui-7-stroke-icons.html">Preview Icons Here</a>'

class About(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    icon = models.CharField(max_length=50, null=True, blank=True, choices=ICONS, help_text=icon_help)
    position = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['position']
        verbose_name_plural = 'About IFA/ Thematic Areas'

    def get_absolute_url(self):
        return reverse('cms:about')


class Contact(models.Model):
    address = models.TextField()
    phone = models.TextField(help_text="Use comma to separate items")
    email = models.TextField(help_text="Use comma to separate items")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.phone

    def get_email(self):
        return self.email.split(",")

    def get_phone(self):
        return self.phone.split(",")


    class Meta:
        verbose_name_plural = 'Contact Details'

    def get_absolute_url(self):
        return reverse('cms:contact')


class Enquiry(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100, blank=True, null=True)
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['-updated']
        verbose_name_plural = 'Enquiries'

cms/forms.py
from django import forms

from .models import Enquiry

class EnquiryForm(forms.ModelForm):
    class Meta:
        model = Enquiry
        fields = ['first_name', 'last_name', 'phone_number','email', 'subject','message']

    def clean_subject(self):
        name = self.cleaned_data.get('subject')
        if name == 'Hello':
            raise forms.ValidationError('Not a valid name')
        return name

cms/views.py
from django.contrib import messages
from django.views.generic import CreateView, ListView, TemplateView
from django.shortcuts import get_object_or_404

from blog.models import Media

from .forms import EnquiryForm
from .models import About, Contact


class HomeView(TemplateView):
    template_name = 'cms/home.html'

    def get_queryset(self):
        pass

    def get_context_data(self, *args, **kwargs):
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        top_story = Media.objects.filter(top_story=1).first()
        # filter by date published
        latest_3_story = Media.objects.exclude(top_story=1).order_by('-id')[:3]
        about_us = About.objects.filter(position=1).first()

        context = {
            'active_page': 'home',
            'top_story': top_story,
            'latest_3_story': latest_3_story,
            'about_us': about_us,
        }
        return context


class ContactView(CreateView):
    template_name = 'cms/contact.html'
    form_class = EnquiryForm
    success_url = '/contact/'

    def form_valid(self, form):
        instance = form.save()
        messages.success(self.request, 'Form submission successful')
        return super(ContactView, self).form_valid(form)

    def get_queryset(self):
        pass

    def get_context_data(self, *args, **kwargs):
        context = super(ContactView, self).get_context_data(*args, **kwargs)
        contact = Contact.objects.first()
        form_class = EnquiryForm

        context = {
            'active_page': 'contact',
            'contact': contact,
            'form': form_class
        }
        return context


class AboutView(ListView):
    template_name = 'cms/about.html'

    def get_queryset(self):
        pass

    def get_context_data(self, *args, **kwargs):
        context = super(AboutView, self).get_context_data(*args, **kwargs)
        about_us = About.objects.filter(section=1).order_by('position')

        context = {
            'active_page': 'about',
            'about_us': about_us,
        }
        return context

cms/templates/cms/about.html
{% extends 'cms/base.html' %}

{% block title %}
    About - Inclusive Friends Association
{% endblock %}

{% block description %}
    About - Inclusive Friends Association
{% endblock %}

{% block keywords %}
    About us, Inclusive Friends Association,
{% endblock %}

{% block page_title %}
    About us
{% endblock %}

{% block page_lead %}
    About us: Our vision and mission
{% endblock %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "About Us" "cms:about" %}
{% endblock %}

{% block content %}
{% load static %}

{% for about in about_us %}
<section class=" {% cycle '' 'background-gray-lightest' %}">
    <div class="container clearfix">
        <div class="row services">
          <div class="col-md-12">
          <h2> {{ about.title }} </h2>

            <p class="lead margin-bottom--medium"> {{ about.description|linebreaksbr }}</p>


          </div>
        </div>
    </div>
</section>
{% endfor %}
<section class="bg-pink">
  <div class="container">
    <h1>Thematic Areas </h1>
    <p class="lead"><strong>Key Areas of Focus</strong></p>
  </div>
</section>
{% for theme in themes %}
<section class=" {% cycle '' 'background-gray-lightest' %}">
    <div class="container clearfix">
        <div class="row services">
            <h2> {{ theme.title }} </h2>
            <div class="col-sm-3">
              <div class="box box-services">
                <div class="icon"><i class="{{ theme.icon }}"></i></div>
              </div>
            </div>
          <div class="col-md-9">
            <p class="lead margin-bottom--medium"> {{ theme.description|linebreaksbr }}</p>
          </div>
        </div>
    </div>
</section>
{% endfor %}


{% endblock %}

cms/templates/cms/footer.html
{% load static %}
<footer class="footer bg-pink">

    <!-- Footer Links -->
    <div class="container text-left">

      <!-- Grid row -->
      <div class="row">

        <!-- Grid column -->
        <div class="col-md-6">
            <div class="row">
                <div class="col-sm-4">
                    <img src="{% static 'cms/img/ifa_logo.png' %}" alt="IFA Logo" width="80px" height="80px">
                </div>
                <div class="col-sm-8">
                    <h5 class="text-uppercase">Inclusive Friends Association IFA. </h5>
                </div>

            </div>
          <!-- Content -->
          <hr>
          <p>
              Hampton Apartment D1 No. 2, Mungo Park close, Asokoro, Area 11, Abuja, Nigeria
              <br>
              For Persons with Disability, By Persons with Disability
          </p>

        </div>
        <!-- Grid column -->


        <!-- Grid column -->
        <div class="col-md-3">

            <!-- Links -->
            <h5 class="text-uppercase">Links</h5>

            <ul class="list-unstyled">
              <li>
                <a href="{% url 'cms:home' %}">Home</a>
              </li>
              <li>
                <a href="{% url 'cms:about' %}">About Us</a>
              </li>
              <li>
                <a href="{% url 'cms:contact' %}">Contact Us</a>
              </li>
              <li>
                  <a href="#" data-toggle="modal" data-target="#login-modal">Donate </a>
              </li>
            </ul>

        </div>
          <!-- Grid column -->

          <!-- Grid column -->
      <div class="col-md-3">

            <!-- Links -->
            <h5 class="text-uppercase">Socials</h5>

            <ul class="list-unstyled">
              <li>
                <a href="https://Facebook.com/inclusivefriends">Facebook</a>
              </li>
              <li>
                <a href="https://instagram.com/inclusivefriends">Instagram</a>
              </li>
              <li>
                <a href="https://twitter.com/inclusivefrnds">Twitter</a>
              </li>
              <li>
                <a href="https://www.youtube.com/channel/UCrLgJ-rH9eFNZ275993s6BQ">Youtube</a>
              </li>
            </ul>

          </div>
          <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

  </footer>
  <!-- Footer -->
<footer class="footer">
  <div class="footer__copyright">
      <div class="container">
        <div class="row bg-copyright-footer ">
          <div class="col-md-12">
              <p>Designed, Developed and Decorated with <i class="pe-7s-like"></i></p>
            <h5 style="color:#fff;">&copy;2019 <a href="https://techamaka.com/" class="external">Techamaka Web Developers </a></h5>
            <!-- <p class="credit" >Template by <a href="https://bootstrapious.com/free-templates" class="external">Bootstrapious templates</a></p> -->
            <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
          </div>

        </div>
      </div>
  </div>
</footer>
<!-- Javascript files-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="{% static 'cms/js/bootstrap.min.js' %}"></script>
<!-- <script src="{% static 'cms/js/jquery.cookie.js' %}"> </script>
<script src="{% static 'cms/js/lightbox.min.js' %}"></script>
<script src="{% static 'cms/js/front.js' %}"></script> -->

<script>
    $(document).ready(function(){
        $('ul#select_currency li').click(function(e){
            var currency = ($(this).find("a").text());
            var note = ($(this).find("a span").text());
             $("span#currency").text(currency);
             $('input#currency_type').val(note);

        });

     });

</script>

cms/templates/cms/form.html
{% load crispy_forms_tags %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% if messages %}
<div class="alert alert-success">
  <strong>Success!</strong>
  {% for message in messages %}
    {{ message }}
  {% endfor %}
</div>
{% endif %}

<div class="row">
    <form class="" action="" method="post">
        {% csrf_token %}

        {{ form|crispy }}

        <div class="col-sm-12">
            <button type="submit" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Submit</button>
        </div>
    </form>

</div>

cms/templates/cms/header.html
{% load static %}
<!-- navbar-->
<header class="header">
  <div role="navigation" class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header"><a href="{% url 'cms:home' %}" class="navbar-brand">
          {% if active_page == 'home' %}
          <img src="{% static 'cms/img/ifa_logo.png' %}" alt="IFA Logo" width="80px" height="80px" class="hidden-sm hidden-xs">
          <span class="hidden-md hidden-lg">IFA.</span>
           {% else %}
           IFA.
           {% endif %}
      </a>
        <div class="navbar-buttons">
          <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-toggle navbar-btn">Menu<i class="fa fa-align-justify"></i></button>
        </div>
      </div>
      <div id="navigation" class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
          <li {% if active_page == 'home' %} class="active" {% endif %}><a href="{% url 'cms:home' %}">Home</a></li>
          <li {% if active_page == 'about' %} class="active" {% endif %}><a href="{% url 'cms:about' %}">About</a></li>
          <li {% if active_page == 'blog' %} class="active" {% endif %}><a href="{% url 'blog:index' %}">News</a></li>

          <!-- <li {% if active_page == 'gallery' %} class="active" {% endif %}><a href="{% url 'cms:gallery' %}">Gallery</a></li> -->
          <li {% if active_page == 'contact' %} class="active" {% endif %}><a href="{% url 'cms:contact' %}">Contact</a></li>
      </ul>

      <a href="#" data-toggle="modal" data-target="#login-modal" {% if active_page == 'home' %} class="btn navbar-btn btn-white pull-left" {% else %} class="btn navbar-btn btn-ghost pull-left" {% endif %} ><i class="fa fa-sign-in"></i>Donate </a>
      </div>
    </div>
  </div>
</header>

<!-- *** Payment MODAL ***_________________________________________________________
-->
<div id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true" class="modal fade">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" data-dismiss="modal" aria-hidden="true" class="close">×</button>
        <h4 id="Login" class="modal-title">Donate to Our Cause </h4>
      </div>
      <div class="modal-body">
        <form action="{% url 'project:donate' %}" method="post">
            {% csrf_token %}


            <div class="form-group">
              <label for="donor_amount">Amount</label>
              <div class="input-group">
                  <div class="input-group-btn">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        <span id="currency">
                            NGN (&#8358;)
                        </span>
                        <input type="hidden" name="currency_type" id="currency_type" value="NGN">

                      <span class="fa fa-caret-down"></span></button>
                    <ul class="dropdown-menu" id="select_currency">
                      <li><a href="javascript:void(0)"><span>NGN</span> (&#8358;)</a></li>
                      <li><a href="javascript:void(0)"><span>USD</span> (&#36;)</a></li>
                      <li><a href="javascript:void(0)"><span>GBP</span> (&#163;)</a></li>
                    </ul>
                  </div>
                <input type="number" id="donor_amount" name="donor_amount" class="form-control" aria-label="Amount (to the nearest currency)" min="1">
                <div class="input-group-addon">
                  <span class="input-group-text">.00</span>
                </div>
              </div>
            </div>

            <div class="form-group">
              <label for="donor_name">Name</label>
              <input id="donor_name" name="donor_name" type="text" class="form-control">
            </div>
            <div class="form-group">
              <label for="donor_email">Email</label>
              <input id="donor_email" name="donor_email" type="email" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="donor_phone_number">Phone Number</label>
              <input id="donor_phone_number" name="donor_phone_number" type="text" class="form-control">
            </div>
            <div class="form-group">
                <div class="checkbox">
                  <label><input id="partner" name="partner" type="checkbox" value="partner">Become a partner</label>
                </div>
            </div>

          <p class="text-center">
            <button type="submit" class="btn btn-primary"  name="pay_now" id="pay-now" title="Pay now"><i class="fa fa-sign-in"></i>Donate Now </button>
          </p>
        </form>
        <p class="text-center text-muted">Hampton Apartment D1 No. 2, Mungo Park close, Asokoro, Area 11, Abuja, Nigeria</p>
        <p class="text-center text-muted">
            <ul>
                <li><strong>UBA Acount Number</strong> 1017672279 </li>
                <li><strong>Diamond Acount Number</strong> 0088547364 </li>
                <li><strong>Acount Name</strong> Inclusive Friends Association </li>
                <li>All Accounts are based in Nigeria Naira</li>
            </ul>
        </p>
      </div>
    </div>
  </div>
</div>
<!-- *** Payment MODAL END ***-->

cms/templates/cms/home.html
<!DOCTYPE html>
<html>
  <head>
      {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Changemakers - Changemakers Leadership and Mentoring</title>
    <meta name="description" content="Changemakers Leadership and Mentoring is A Nigerian Based Non-Governmental Organisation (NGO) for People With Disabilities (PWD). IFA works with local and international Organisation to provide access and inclusiveness of PWDs">
    <meta name="keywords" content="NGO, PWD, Inclusive Friends, Nigeria, Organisation, Access, Inclusive, Association">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'cms/css/bootstrap.min.css' %}">
    <!-- Font Awesome & Pixeden Icon Stroke icon font-->
    <link rel="stylesheet" href="{% static 'cms/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'cms/css/pe-icon-7-stroke.css' %}">
    <!-- Google fonts - Roboto Condensed & Roboto-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:700|Roboto:300,400">
    <!-- lightbox-->
    <link rel="stylesheet" href="{% static 'cms/css/lightbox.min.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'cms/css/style.pink.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'cms/css/custom.css' %}">
    <!-- Favicon-->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'cms/img/favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'cms/img/favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'cms/img/favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'cms/img/favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'cms/img/favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'cms/img/favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'cms/img/favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'cms/img/favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'cms/img/favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'cms/img/favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'cms/img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'cms/img/favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'cms/img/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'cms/img/favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'cms/img/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
        <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-129577494-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-129577494-1');
    </script>
  </head>
  <body class="home">

      {% include "cms/header.html" %}

    <div id="carousel-home" data-ride="carousel" class="carousel slide carousel-fullscreen carousel-fade">
      <!-- Wrapper for slides-->
      <div role="listbox" class="carousel-inner">
        <div style="background-image: url('{% static "cms/img/inclusive_friends.jpg" %}');" class="item active">
          <div class="overlay"></div>
          <div class="carousel-caption">
            <h1 class="super-heading">Changemakers Leadership and Mentoring</h1>
            <p class="super-paragraph">An NGO for and by Persons with Disability.</p>
        </div>
        </div>
      </div>
    </div>
    <section class="bg-pink negative-margin">
      <div class="container">

        <h2> {{ top_story.title }}</h2>
        <p class="lead">{{ top_story.body | truncatewords:50 }}.</p>
        <p> <a href="{{ top_story.get_absolute_url }}" class="btn btn-white">Continue reading our top story   </a></p>
      </div>
    </section>
    <section class="section--padding-bottom-small">
      <div class="container">
        <h2 class="text-center">News & Events </h2>
        <hr>
        <div class="row">
            {% for story in latest_3_story %}
            <div class="col-sm-4">
              <div class="post">
                <div class="image"><a href="{{ story.get_absolute_url }}"><img src="{{ story.image_set.first.image.url }}" alt="{{ story.image_set.first.description }}" class="img-responsive"></a></div>
                <h3><a href="{{ story.get_absolute_url }}">{{ story.title }}</a></h3>
                <p class="post__intro">
                    {{ story.body | truncatewords:25 }}
                </p>
                <p class="read-more"><a href="{{ story.get_absolute_url }}" class="btn btn-ghost">Continue reading     </a></p>
              </div>
            </div>
            {% endfor %}
        </div>
      </div>
    </section>
    <!--   *** SERVICES ***-->
    <section class="background-gray-lightest">
      <div class="container clearfix">
        <div class="row services">
          <div class="col-md-12">
            <h2>About Us</h2>
            <p class="lead margin-bottom--medium">
                {{ about_us.description | truncatewords:50 }} <a href="{% url 'cms:about' %}" class="">See More About Us </a>
            </p>
            <div class="row">
                <div class="col-sm-12">
                    <h3>Our Thematic Areas</h3>
                </div>
                <div class="row">
                    {% for theme in thematic_areas %}
                        <div class="col-sm-12">
                          <div class="box box-services">
                            <div class="icon"><i class="{{ theme.icon }}"></i></div>
                            <h4 class="services-heading">{{ theme.title }} </h4>
                            <p>{{ theme.description | truncatewords:45 }}</p>
                          </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-sm-12">
                  <div class="box box-services">
                    <div class="icon"><i class="pe-7s-more"></i></div>
                    <h4 class="services-heading">Changemakers Leadership and Mentoring (IFA) </h4>
                    <p> An NGO for and by Persons with Disability... <a href="{% url 'cms:about' %}" class="btn btn-ghost"> See All The Places Our Impact is Felt</a>
                    </p>
                  </div>
                </div>



            </div>

          </div>
        </div>
      </div>
    </section>
    <!--   *** SERVICES END ***-->
    <section class="section--padding-bottom-small">
      <div class="container">
        <h2 class="text-center">Projects </h2>
        <hr>
        {% for pro in projects  %}
        <div class="row">
            <div class="col-sm-4">
              <div class="post">
                <div class="image"><a href="{{ pro.get_absolute_url }}"><img src="{{ pro.image_set.first.image.url }}" alt="{{ pro.image_set.first.description }}" class="img-responsive img-thumbnail"></a></div>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="text-left">
                <h3><a href="{{ pro.get_absolute_url }}">{{ pro.title }}</a></h3>
                <p class="post__intro">{{ pro.description|truncatewords:80}}</p>
                <p class="read-more"><a href="{{ pro.get_absolute_url }}" class="btn btn-ghost">See Project Details  </a></p>
              </div>
            </div>
        </div>
        {% endfor %}
      </div>
    </section>
    <!-- Footer -->
    {% include "cms/footer.html" %}
  </body>
</html>